/**
 * One permission per tenant-admin sidebar destination.
 * Checked after the stricter create/edit rules in nav-permissions.ts.
 * Longest prefix wins.
 */

export const ADMIN_MENU_EXACT: Record<string, string> = {
  "/admin": "view_dashboard",
  "/admin/subscriptions": "view_tenant_subscription",
  "/admin/subscription": "view_tenant_subscription",

  "/admin/members": "view_members",
  "/admin/members/subscriptions": "view_member_property_subscriptions",
  "/admin/member-subscriptions/bulk": "bulk_member_subscriptions",
  "/admin/bulk-upload/members": "bulk_upload_members",

  "/admin/users": "view_users",
  "/admin/roles": "view_roles",
  "/admin/permissions": "view_permissions",

  "/admin/wallets": "view_wallets",
  "/admin/wallets/transactions": "view_wallet_transactions",
  "/admin/wallets/pending": "view_pending_wallets",
  "/admin/wallet-transfer": "manage_wallet_transfers",
  "/admin/bulk-upload/wallet-transfers": "bulk_wallet_transfers",

  "/admin/contributions": "view_contributions",
  "/admin/post-contribution": "create_contributions",
  "/admin/contribution-plans": "view_contribution_plans",
  "/admin/bulk-upload/contributions": "bulk_upload_contributions",
  "/admin/bulk-upload/contribution-asset-repayments": "bulk_contribution_repayments",

  "/admin/equity-contributions": "view_equity_contributions",
  "/admin/equity-plans": "manage_equity_plans",
  "/admin/bulk-upload/equity-contributions": "bulk_upload_equity_contributions",
  "/admin/bulk-upload/equity-asset-repayments": "bulk_equity_repayments",

  "/admin/loans": "view_loans",
  "/admin/loans/stoppage": "manage_loan_stoppage",
  "/admin/loan-repayments": "manage_loan_repayments",
  "/admin/loan-products": "view_loan_products",
  "/admin/bulk-upload/loans": "bulk_upload_loans",
  "/admin/bulk-upload/loan-repayments": "bulk_upload_loan_repayments",

  "/admin/refunds": "view_refunds",
  "/admin/refund-member": "manage_refunds",
  "/admin/bulk-upload/refund": "bulk_refunds",

  "/admin/mortgages": "view_mortgages",
  "/admin/mortgages/bulk-repay": "bulk_mortgage_repayments",
  "/admin/mortgages/new": "create_mortgages",
  "/admin/mortgage-providers": "view_mortgage_providers",
  "/admin/bulk-upload/mortgages": "bulk_upload_mortgages",
  "/admin/internal-mortgages": "view_internal_mortgages",
  "/admin/bulk-upload/internal-mortgages": "bulk_internal_mortgages",
  "/admin/bulk-upload/internal-mortgage-repayments": "bulk_internal_mortgage_repayments",
  "/admin/bulk-upload/mortgage-repayments": "bulk_mortgage_repayments",
  "/admin/tools/mortgage-calculators": "view_mortgage_calculators",
  "/admin/bulk-upload/rollbacks": "rollback_financial_transactions",
  "/admin/financial-rollbacks": "rollback_financial_transactions",

  "/admin/properties": "view_properties",
  "/admin/eoi-forms": "manage_eoi_forms",
  "/admin/property-payment-plans": "view_property_payment_plans",
  "/admin/bulk-upload/properties": "bulk_upload_properties",
  "/admin/bulk-upload/property-subscribers": "bulk_property_subscribers",
  "/admin/bulk-upload/property-payments": "bulk_property_payments",
  "/admin/bulk-upload/issued-documents": "issue_documents",
  "/admin/house-repayments": "record_house_repayments",
  "/admin/reports/properties": "view_property_reports",
  "/admin/valuations": "view_valuations",
  "/admin/change-requests": "view_change_requests",
  "/admin/property-improvements": "view_property_improvements",

  "/admin/lands": "view_lands",
  "/admin/land-eoi-forms": "manage_land_eoi",
  "/admin/land-subscriptions/new": "manage_land_subscriptions",
  "/admin/land-subscriptions/mass-allocate": "manage_land_subscriptions",
  "/admin/bulk-upload/lands": "bulk_upload_lands",
  "/admin/bulk-upload/land-subscriptions": "bulk_land_subscriptions",
  "/admin/bulk-upload/land-payments": "bulk_land_payments",
  "/admin/reports/land": "view_land_reports",

  "/admin/investment-plans": "view_investment_plans",
  "/admin/investments": "view_investments",
  "/admin/collaterals": "view_collateral",
  "/admin/bulk-upload/investments": "bulk_upload_investments",
  "/admin/investment-withdrawal-requests": "view_investment_withdrawals",

  "/admin/statutory-charges": "view_statutory_charges",
  "/admin/statutory-charges/definitions": "view_statutory_charges",
  "/admin/statutory-charges/types": "manage_statutory_charge_types",
  "/admin/statutory-charges/payments/new": "manage_statutory_charge_payments",
  "/admin/statutory-charges/payments": "manage_statutory_charge_payments",
  "/admin/statutory-charges/departments": "manage_statutory_charge_departments",

  "/admin/property-management/estates": "manage_property_estates",
  "/admin/property-management/maintenance": "view_maintenance",
  "/admin/property-management/reports": "view_property_ops_reports",
  "/admin/property-management/allottees": "manage_property_allottees",
  "/admin/property-management/allottees/new": "manage_property_allottees",
  "/admin/property-management/allottees/mass-allocate": "manage_property_allottees",

  "/admin/resident-association": "ra.estate.view",
  "/admin/resident-association/associations": "ra.estate.manage",
  "/admin/resident-association/houses": "ra.house.view",
  "/admin/resident-association/charges": "ra.charge.manage",
  "/admin/resident-association/payments": "ra.payment.view",
  "/admin/resident-association/discrepancies": "ra.discrepancy.view",
  "/admin/resident-association/revenue": "ra.revenue.view",
  "/admin/resident-association/expenditures": "ra.expenditure.manage",
  "/admin/resident-association/bank-accounts": "ra.settings.manage",
  "/admin/resident-association/notices": "ra.notice.manage",

  "/admin/blockchain": "view_blockchain",
  "/admin/blockchain/wallets": "manage_blockchain_wallets",
  "/admin/blockchain/setup": "manage_blockchain_setup",

  "/admin/mail-service": "view_mail",
  "/admin/mail-service/compose": "compose_mail",
  "/admin/mail-service/inbox": "view_mail_inbox",
  "/admin/mail-service/sent": "view_mail_sent",
  "/admin/mail-service/outbox": "view_mail_outbox",
  "/admin/mail-service/drafts": "view_mail_drafts",

  "/admin/reports/members": "view_member_reports",
  "/admin/reports/financial": "view_financial_reports",
  "/admin/reports/contributions": "view_contribution_reports",
  "/admin/reports/refunds": "view_refund_reports",
  "/admin/reports/equity-contributions": "view_equity_reports",
  "/admin/reports/investments": "view_investment_reports",
  "/admin/reports/loans": "view_loan_reports",
  "/admin/reports/mail-service": "view_mail_reports",
  "/admin/reports/audit": "view_audit_reports",

  "/admin/accounting": "view_accounting",
  "/admin/accounting/accounts": "manage_chart_of_accounts",
  "/admin/accounting/rules": "manage_posting_rules",
  "/admin/accounting/periods": "manage_financial_periods",
  "/admin/accounting/journals": "post_journal_entries",
  "/admin/accounting/reports": "view_gl_reports",
  "/admin/accounting/statements": "generate_member_statements",
  "/admin/accounting/property-ledger": "view_property_ledger",

  "/admin/ecpm": "view_ecpm",
  "/admin/ecpm/estates": "manage_ecpm_estates",
  "/admin/ecpm/projects": "manage_ecpm_projects",
  "/admin/ecpm/parties": "manage_ecpm_parties",
  "/admin/ecpm/drawings": "manage_ecpm_drawings",
  "/admin/ecpm/boqs": "manage_ecpm_boqs",
  "/admin/ecpm/quotations": "manage_ecpm_quotations",
  "/admin/ecpm/contracts": "manage_ecpm_contracts",
  "/admin/ecpm/approvals": "approve_ecpm_documents",
  "/admin/ecpm/site-ops": "manage_ecpm_site_ops",
  "/admin/ecpm/procurement": "manage_ecpm_procurement",
  "/admin/ecpm/handover": "manage_ecpm_handover",
  "/admin/ecpm/ai": "manage_ecpm_ai",
  "/admin/ecpm/reports": "view_ecpm_reports",
  "/admin/ecpm/audit": "view_ecpm_audit",

  "/admin/office": "view_office",
  "/admin/notifications": "view_notifications",
  "/admin/announcements": "view_announcements",
  "/admin/documents": "view_documents",
  "/admin/issued-documents": "view_issued_documents",
  "/admin/payment-receipts": "view_receipts",
  "/admin/issued-documents/letterhead": "manage_letterhead_settings",
  "/admin/issued-documents/templates": "manage_document_templates",
  "/admin/landing-page": "manage_landing_page",
  "/admin/landing-page/templates": "manage_landing_page_templates",
  "/admin/payment-gateways": "view_payment_gateways",
  "/admin/payment-approvals": "manage_payment_approvals",
  "/admin/white-label": "view_white_label",
  "/admin/custom-domains": "manage_custom_domains",
  "/admin/audit-logs": "view_audit_logs",
  "/admin/activity-logs": "view_activity_logs",
  "/admin/settings": "manage_settings",
  "/admin/platform-config": "manage_platform_config",
  "/admin/payment-routing": "manage_payment_routing",
  "/admin/contact-centre": "manage_contact_centre",
}

/** Longer prefixes first so /admin/loans/stoppage is not treated as the loans list. */
export const ADMIN_MENU_PREFIXES: Array<{ prefix: string; permission: string }> = [
  { prefix: "/admin/property-management/allottees", permission: "manage_property_allottees" },
  { prefix: "/admin/property-management/estates", permission: "manage_property_estates" },
  { prefix: "/admin/property-management/maintenance", permission: "view_maintenance" },
  { prefix: "/admin/property-management/reports", permission: "view_property_ops_reports" },
  { prefix: "/admin/resident-association/associations", permission: "ra.estate.manage" },
  { prefix: "/admin/resident-association/houses", permission: "ra.house.view" },
  { prefix: "/admin/resident-association/charges", permission: "ra.charge.manage" },
  { prefix: "/admin/resident-association/payments", permission: "ra.payment.view" },
  { prefix: "/admin/resident-association/discrepancies", permission: "ra.discrepancy.view" },
  { prefix: "/admin/resident-association/revenue", permission: "ra.revenue.view" },
  { prefix: "/admin/resident-association/expenditures", permission: "ra.expenditure.manage" },
  { prefix: "/admin/resident-association/bank-accounts", permission: "ra.settings.manage" },
  { prefix: "/admin/resident-association/notices", permission: "ra.notice.manage" },
  { prefix: "/admin/resident-association", permission: "ra.estate.view" },
  { prefix: "/admin/accounting/accounts", permission: "manage_chart_of_accounts" },
  { prefix: "/admin/accounting/rules", permission: "manage_posting_rules" },
  { prefix: "/admin/accounting/periods", permission: "manage_financial_periods" },
  { prefix: "/admin/accounting/journals", permission: "post_journal_entries" },
  { prefix: "/admin/accounting/reports", permission: "view_gl_reports" },
  { prefix: "/admin/accounting/statements", permission: "generate_member_statements" },
  { prefix: "/admin/accounting/property-ledger", permission: "view_property_ledger" },
  { prefix: "/admin/accounting", permission: "view_accounting" },
  { prefix: "/admin/ecpm/estates", permission: "manage_ecpm_estates" },
  { prefix: "/admin/ecpm/projects", permission: "manage_ecpm_projects" },
  { prefix: "/admin/ecpm/parties", permission: "manage_ecpm_parties" },
  { prefix: "/admin/ecpm/drawings", permission: "manage_ecpm_drawings" },
  { prefix: "/admin/ecpm/boqs", permission: "manage_ecpm_boqs" },
  { prefix: "/admin/ecpm/quotations", permission: "manage_ecpm_quotations" },
  { prefix: "/admin/ecpm/contracts", permission: "manage_ecpm_contracts" },
  { prefix: "/admin/ecpm/approvals", permission: "approve_ecpm_documents" },
  { prefix: "/admin/ecpm/site-ops", permission: "manage_ecpm_site_ops" },
  { prefix: "/admin/ecpm/procurement", permission: "manage_ecpm_procurement" },
  { prefix: "/admin/ecpm/handover", permission: "manage_ecpm_handover" },
  { prefix: "/admin/ecpm/ai", permission: "manage_ecpm_ai" },
  { prefix: "/admin/ecpm/reports", permission: "view_ecpm_reports" },
  { prefix: "/admin/ecpm/audit", permission: "view_ecpm_audit" },
  { prefix: "/admin/ecpm", permission: "view_ecpm" },
  { prefix: "/admin/mail-service/inbox", permission: "view_mail_inbox" },
  { prefix: "/admin/mail-service/sent", permission: "view_mail_sent" },
  { prefix: "/admin/mail-service/outbox", permission: "view_mail_outbox" },
  { prefix: "/admin/mail-service/drafts", permission: "view_mail_drafts" },
  { prefix: "/admin/mail-service/compose", permission: "compose_mail" },
  { prefix: "/admin/mail-service", permission: "view_mail" },
  { prefix: "/admin/issued-documents/letterhead", permission: "manage_letterhead_settings" },
  { prefix: "/admin/issued-documents/templates", permission: "manage_document_templates" },
  { prefix: "/admin/issued-documents", permission: "view_issued_documents" },
  { prefix: "/admin/statutory-charges/types", permission: "manage_statutory_charge_types" },
  { prefix: "/admin/statutory-charges/departments", permission: "manage_statutory_charge_departments" },
  { prefix: "/admin/statutory-charges/payments", permission: "manage_statutory_charge_payments" },
  { prefix: "/admin/statutory-charges/definitions", permission: "view_statutory_charges" },
  { prefix: "/admin/statutory-charges", permission: "view_statutory_charges" },
  { prefix: "/admin/blockchain/wallets", permission: "manage_blockchain_wallets" },
  { prefix: "/admin/blockchain/setup", permission: "manage_blockchain_setup" },
  { prefix: "/admin/blockchain", permission: "view_blockchain" },
  { prefix: "/admin/wallets/transactions", permission: "view_wallet_transactions" },
  { prefix: "/admin/wallets/pending", permission: "view_pending_wallets" },
  { prefix: "/admin/wallets", permission: "view_wallets" },
  { prefix: "/admin/loans/stoppage", permission: "manage_loan_stoppage" },
  { prefix: "/admin/lands", permission: "view_lands" },
  { prefix: "/admin/land-subscriptions", permission: "manage_land_subscriptions" },
  { prefix: "/admin/land-eoi-forms", permission: "manage_land_eoi" },
  { prefix: "/admin/mortgages", permission: "view_mortgages" },
  { prefix: "/admin/reports", permission: "view_reports" },
]

export function permissionForAdminMenu(href: string): string | null {
  const normalized = href.replace(/\/+$/, "") || "/admin"
  const exact = ADMIN_MENU_EXACT[normalized]
  if (exact) return exact
  for (const rule of ADMIN_MENU_PREFIXES) {
    if (normalized === rule.prefix || normalized.startsWith(`${rule.prefix}/`)) {
      return rule.permission
    }
  }
  return null
}
